### PR TITLE
Refactored code

### PR DESCRIPTION
**Pull request by ghillu**
An attempt to solve issue #6 #8 #9

### CODE REVIEW

**Comment by nkkumawat** [comment]
Gaurav resolve conflicts and then generate PR.

**Comment by ghillu** [comment]
Sir, done.

**Comment by KaranSharma-gawds** [comment]
```start_app()``` needs definition

**Comment by ghillu** [comment]
Okay! Done.

**Comment by KaranSharma-gawds** [comment]
Looks good to me! Great Effort  👍

**Pull request merged**
